ServerEvents.recipes(event => {
    event.remove({id: 'minecraft:netherite_scrap_from_blasting'})
    event.remove({id: 'minecraft:netherite_scrap'})
    event.remove({id: 'minecraft:netherite_ingot'})
    event.remove({id: 'mekanism:processing/netherite/ancient_debris_to_scrap'})
    event.remove({id: 'mekanism:processing/netherite/ancient_debris_to_dirty_scrap'})
    event.remove({id: 'mekanism:processing/netherite/dirty_scrap_to_scrap'})
    event.remove({id: 'cyclic:crusher/debris'})
    event.remove({id: 'projecte:watch_of_flowing_time',})
    event.remove({id: 'projecte:collector_mk1'})
    event.remove({id: 'projectexpansion:collector/basic'})
    event.remove({id: 'enderio:smelting/minecraft/netherite_scrap'})
    event.remove({id: 'projecte:dm_axe'})
    event.remove({id: 'projecte:dm_boots'})
    event.remove({id: 'projecte:dm_chestplate'})
    event.remove({id: 'projecte:dm_hammer'})
    event.remove({id: 'projecte:dm_helmet'})
    event.remove({id: 'projecte:dm_hoe'})
    event.remove({id: 'projecte:dm_leggings'})
    event.remove({id: 'projecte:dm_pick'})
    event.remove({id: 'projecte:dm_shears'})
    event.remove({id: 'projecte:dm_shovel'})
    event.remove({id: 'projecte:dm_sword'})
})